"""create track album playlist saved

Revision ID: f90a7f8469e5
Revises: d748da0e3bd3
Create Date: 2022-04-24 20:22:09.077641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f90a7f8469e5'
down_revision = 'd748da0e3bd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('size', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.Integer(), nullable=False),
    sa.Column('genre', sa.Integer(), nullable=False),
    sa.Column('album_type', sa.String(length=6), nullable=False),
    sa.Column('release_date', sa.Date(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist'], ['users.id'], name='fk_albums_users_id_artist'),
    sa.ForeignKeyConstraint(['genre'], ['genres.id'], name='fk_albums_genres_id_genre'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('author', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author'], ['users.id'], name='fk_playlists_users_id_author'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('albums_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('album', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album'], ['albums.id'], name='fk_albums_images_albums_album_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image'], ['images.id'], name='fk_albums_images_images_image_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.Integer(), nullable=True),
    sa.Column('playlist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image'], ['images.id'], name='fk_playlists_images_images_image_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist'], ['playlists.id'], name='fk_playlists_images_playlists_playlist_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('playlist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist'], ['playlists.id'], name='fk_playlists_users_playlists_playlist_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_playlists_users_users_user_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_albums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('album', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album'], ['albums.id'], name='fk_saved_albums_albums_id_album'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_saved_albums_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'album', name='uc_saved_albums_user_album')
    )
    op.create_table('saved_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('playlist', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['playlist'], ['playlists.id'], name='fk_saved_playlists_playlists_id_playlist'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_saved_playlists_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'playlist', name='uc_saved_playlists_user_playlist')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('artist', sa.Integer(), nullable=False),
    sa.Column('album', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=255), nullable=False),
    sa.Column('is_playable', sa.Boolean(), nullable=False),
    sa.Column('explicit', sa.Boolean(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['album'], ['albums.id'], name='fk_tracks_albums_id_album'),
    sa.ForeignKeyConstraint(['artist'], ['users.id'], name='fk_tracks_users_id_artist'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlists_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track', sa.Integer(), nullable=True),
    sa.Column('playlist', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist'], ['playlists.id'], name='fk_playlists_tracks_playlists_playlist_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track'], ['tracks.id'], name='fk_playlists_tracks_tracks_track_id', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('track', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['track'], ['tracks.id'], name='fk_saved_tracks_tracks_id_track'),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name='fk_saved_tracks_users_id_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'track', name='uc_saved_tracks_user_track')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_tracks')
    op.drop_table('playlists_tracks')
    op.drop_table('tracks')
    op.drop_table('saved_playlists')
    op.drop_table('saved_albums')
    op.drop_table('playlists_users')
    op.drop_table('playlists_images')
    op.drop_table('albums_images')
    op.drop_table('playlists')
    op.drop_table('albums')
    op.drop_table('images')
    op.drop_table('genres')
    # ### end Alembic commands ###
